### PR TITLE
Run tests on PHP 8.3 and update test suite

### PR DESCRIPTION
**Pull request by yadaiio**
This pull request builds on top of #46, #47 and #48.

References: https://github.com/clue/reactphp-csv/pull/33, https://github.com/reactphp/socket/pull/300 and https://github.com/reactphp/socket/pull/299.

After this pull request is merged, we can continue with #53.

### CODE REVIEW

**Review by SimonFrings — CHANGES_REQUESTED** [review]
It appears that we're still using the old `ubuntu-20.04` in our PHPUnit job within the `ci.yml` file. I believe this should also be updated to `ubuntu-22.04`, just like you did for the PHPUnit-hhvm job.

**Comment by yadaiio** [comment]
Tysm @SimonFrings for sharpening my eyes for this ! I totally didn't saw this in the first place. Whoops. But it should be alright now! 🥳

**Review by SimonFrings — APPROVED** [review]
Thanks for applying the changes, looking good :+1:

**Review by clue — APPROVED** [review]
@yadaiio Thanks for looking into this, changes LGTM! :shipit:

**Pull request merged**
